import { useState } from "react";
import "./App.css";
import ChatAssistant from "./ChatAssistant";

function App() {
  const [page, setPage] = useState("home");
  const [initialPrompt, setInitialPrompt] = useState("");

  // Quiz state
  const [questionNumber, setQuestionNumber] = useState(0);
  const [score, setScore] = useState(0);

  // Scam checker state
  const [scamMessage, setScamMessage] = useState("");
  const [scamResult, setScamResult] = useState(null);
  const [isCheckingScam, setIsCheckingScam] = useState(false);

  // USSD state
  const [ussdStep, setUssdStep] = useState("menu");
  const [ussdInput, setUssdInput] = useState("");

  const openAssistant = (prompt = "") => {
    setInitialPrompt(prompt);
    setPage("assistant");
  };

  // ==============================
  // QUIZZES
  // ==============================

  const questions = [
    {
      question: "Should you share your mobile money PIN with someone?",
      options: ["Yes", "No"],
      correct: "No",
    },
    {
      question: "What should you do before clicking a suspicious link?",
      options: [
        "Click it immediately",
        "Check and verify the link",
        "Share it with everyone",
      ],
      correct: "Check and verify the link",
    },
    {
      question: "Which password is stronger?",
      options: ["123456", "password", "MyP@ssw0rd!2026"],
      correct: "MyP@ssw0rd!2026",
    },
  ];

  const emailQuestions = [
    {
      question: "What is email mainly used for?",
      options: [
        "Sending and receiving messages",
        "Cooking food",
        "Taking photos",
        "Charging a phone",
      ],
      correct: "Sending and receiving messages",
    },
    {
      question: "Which button is commonly used to start writing a new email?",
      options: ["Delete", "Compose", "Refresh", "Download"],
      correct: "Compose",
    },
    {
      question:
        "What should you do if you receive an email from an unknown sender with a suspicious attachment?",
      options: [
        "Open the attachment immediately",
        "Forward it to everyone",
        "Be careful and avoid opening it",
        "Reply with your password",
      ],
      correct: "Be careful and avoid opening it",
    },
  ];

  const aiQuestions = [
    {
      question: "What is Artificial Intelligence (AI)?",
      options: [
        "Technology that allows computers to perform tasks that normally require human intelligence",
        "A type of mobile phone",
        "A social media application",
        "A computer cable",
      ],
      correct:
        "Technology that allows computers to perform tasks that normally require human intelligence",
    },
    {
      question: "Which of these is an example of Artificial Intelligence?",
      options: [
        "A voice assistant answering questions",
        "A notebook",
        "A USB cable",
        "A normal light bulb",
      ],
      correct: "A voice assistant answering questions",
    },
    {
      question:
        "What should you do before trusting important information generated by AI?",
      options: [
        "Share it immediately",
        "Verify the information",
        "Ignore it completely",
        "Send it to everyone",
      ],
      correct: "Verify the information",
    },
  ];

  // ==============================
  // SCAM ANALYZER
  // ==============================

  const analyzeScamMessage = (messageToAnalyze = scamMessage) => {
    if (!messageToAnalyze.trim()) return;

    setIsCheckingScam(true);
    setScamResult(null);

    const message = messageToAnalyze.toLowerCase();
    let scamScore = 0;
    const warningSigns = [];

    if (
      message.includes("urgent") ||
      message.includes("immediately") ||
      message.includes("now") ||
      message.includes("hurry") ||
      message.includes("minutes")
    ) {
      scamScore += 20;
      warningSigns.push({
        icon: "⏰",
        title: "Creates urgency",
        description:
          "The sender is pressuring you to act quickly instead of giving you time to verify the message.",
      });
    }

    if (
      message.includes("pin") ||
      message.includes("otp") ||
      message.includes("password") ||
      message.includes("passcode") ||
      message.includes("verification code")
    ) {
      scamScore += 35;
      warningSigns.push({
        icon: "🔐",
        title: "Requests sensitive information",
        description:
          "Legitimate organizations should not ask you to reveal your PIN, password, or OTP.",
      });
    }

    if (
      message.includes("send money") ||
      message.includes("pay") ||
      message.includes("payment") ||
      message.includes("transfer") ||
      message.includes("fee") ||
      message.includes("deposit")
    ) {
      scamScore += 25;
      warningSigns.push({
        icon: "💰",
        title: "Requests money",
        description: "The message asks you to send money or make a payment.",
      });
    }

    if (
      message.includes("won") ||
      message.includes("winner") ||
      message.includes("prize") ||
      message.includes("reward") ||
      message.includes("congratulations") ||
      message.includes("lottery")
    ) {
      scamScore += 20;
      warningSigns.push({
        icon: "🎁",
        title: "Unexpected reward",
        description:
          "The message promises a prize or reward that you may not have expected.",
      });
    }

    if (
      message.includes("http://") ||
      message.includes("https://") ||
      message.includes("www.")
    ) {
      scamScore += 15;
      warningSigns.push({
        icon: "🔗",
        title: "Contains a link",
        description:
          "Be careful with links in unexpected messages. Verify the destination before opening them.",
      });
    }

    if (
      message.includes("account will be closed") ||
      message.includes("account will be blocked") ||
      message.includes("arrest") ||
      message.includes("police") ||
      message.includes("legal action")
    ) {
      scamScore += 20;
      warningSigns.push({
        icon: "⚠️",
        title: "Uses fear or threats",
        description:
          "The sender may be using fear or threats to pressure you into acting.",
      });
    }

    scamScore = Math.min(scamScore, 100);

    let riskLevel = "LOW";
    let riskDescription =
      "We found few obvious warning signs, but always verify unexpected messages.";

    if (scamScore >= 70) {
      riskLevel = "HIGH";
      riskDescription =
        "This message contains several common warning signs associated with scams.";
    } else if (scamScore >= 40) {
      riskLevel = "SUSPICIOUS";
      riskDescription =
        "This message contains warning signs that you should investigate before taking action.";
    } else if (scamScore >= 20) {
      riskLevel = "CAUTION";
      riskDescription =
        "There are some warning signs. Be careful and verify the sender.";
    }

    let scamCategory = "General Scam";

    if (
      message.includes("mobile money") ||
      message.includes("momo") ||
      message.includes("airtel money") ||
      message.includes("mtn")
    ) {
      scamCategory = "Mobile Money Scam";
    } else if (
      message.includes("job") ||
      message.includes("employment") ||
      message.includes("vacancy") ||
      message.includes("salary")
    ) {
      scamCategory = "Job Scam";
    } else if (
      message.includes("scholarship") ||
      message.includes("university") ||
      message.includes("school")
    ) {
      scamCategory = "Education Scam";
    } else if (
      message.includes("prize") ||
      message.includes("winner") ||
      message.includes("lottery")
    ) {
      scamCategory = "Prize Scam";
    } else if (
      message.includes("bank") ||
      message.includes("password") ||
      message.includes("otp")
    ) {
      scamCategory = "Account / Identity Scam";
    }

    const result = {
      score: scamScore,
      riskLevel,
      riskDescription,
      warningSigns,
      scamCategory,
    };

    setTimeout(() => {
      setScamResult(result);
      setIsCheckingScam(false);
    }, 900);
  };

  // ==============================
  // USSD FUNCTIONS
  // ==============================

  const resetUSSD = () => {
    setUssdStep("menu");
    setUssdInput("");
  };

  const handleUSSDMessageCheck = () => {
    if (!ussdInput.trim()) return;

    analyzeScamMessage(ussdInput);
    setUssdInput("");

    setTimeout(() => {
      setUssdStep("result");
    }, 950);
  };

  // ==============================
  // QUIZ FUNCTIONS
  // ==============================

  const startQuiz = (quizPage) => {
    setQuestionNumber(0);
    setScore(0);
    setPage(quizPage);
  };

  const answerQuestion = (option, quiz, resultPage) => {
    if (option === quiz[questionNumber].correct) {
      setScore((currentScore) => currentScore + 1);
    }

    if (questionNumber < quiz.length - 1) {
      setQuestionNumber((currentQuestion) => currentQuestion + 1);
    } else {
      setPage(resultPage);
    }
  };

  // ==============================
  // HOME
  // ==============================

  if (page === "home") {
    return (
      <div className="app">
        <h1>Digital Buddy</h1>

        <p className="subtitle">
          Learn, stay safe, and understand technology.
        </p>

        <h2>What would you like to do?</h2>

        <div className="cards">
          <button className="card" onClick={() => setPage("learn")}>
            <div className="icon">📚</div>
            <h3>Learn Digital Skills</h3>
            <p>Learn how to use technology safely.</p>
          </button>

          <button className="card" onClick={() => setPage("scamCheck")}>
            <div className="icon">🛡️</div>
            <h3>Check For Scams</h3>
            <p>Check suspicious messages.</p>
          </button>

          <button className="card" onClick={() => openAssistant("")}>
            <div className="icon">🤖</div>
            <h3>Ask Digital Assistant</h3>
            <p>Ask questions about technology.</p>
          </button>
        </div>
      </div>
    );
  }

  // ==============================
  // AI ASSISTANT
  // ==============================

  if (page === "assistant") {
    return (
      <div className="app">
        <button className="back-button" onClick={() => setPage("home")}>
          ← Back
        </button>

        <ChatAssistant
          initialPrompt={initialPrompt}
          onBack={() => setPage("home")}
        />
      </div>
    );
  }

  // ==============================
  // LEARNING PAGE
  // ==============================

  if (page === "learn") {
    return (
      <div className="app">
        <button onClick={() => setPage("home")}>← Back</button>

        <h1>📚 Learn Digital Skills</h1>
        <p>Choose a topic you would like to learn.</p>

        <button
          className="ussd-button"
          onClick={() => {
            setUssdInput("");
            setUssdStep("learnMenu");
            setPage("ussd");
          }}
        >
          📱 Use USSD to Learn Offline
        </button>

        <button
          className="lesson-button"
          onClick={() => setPage("cybersecurity")}
        >
          <h3>🔐 Cybersecurity</h3>
          <p>Learn how to protect your accounts and personal information.</p>
        </button>

        <button className="lesson-button" onClick={() => setPage("email")}>
          <h3>📧 Email</h3>
          <p>Learn how to create and use email safely.</p>
        </button>

        <button className="lesson-button" onClick={() => setPage("ai")}>
          <h3>🤖 Artificial Intelligence</h3>
          <p>Learn how to use AI safely and effectively.</p>
        </button>
      </div>
    );
  }

  // ==============================
  // USSD PAGE
  // ==============================

  if (page === "ussd") {
    return (
      <div className="app ussd-page">
        <button
          className="back-button"
          onClick={() => {
            setPage("learn");
            setUssdInput("");
          }}
        >
          ← Back
        </button>

        <div className="ussd-header">
          <div className="ussd-large-icon">
            {["learnMenu", "ussdCybersecurity", "ussdEmail", "ussdAI"].includes(
              ussdStep,
            )
              ? "📚"
              : "📱"}
          </div>

          {["learnMenu", "ussdCybersecurity", "ussdEmail", "ussdAI"].includes(
            ussdStep,
          ) ? (
            <>
              <h1>Offline Learning</h1>
              <p>Learn digital skills without using internet data.</p>
            </>
          ) : (
            <>
              <h1>Offline Safety Check</h1>
              <p>Check suspicious messages without using internet data.</p>
            </>
          )}
        </div>

        <div className="phone-container">
          <div className="phone-screen">
            <div className="network-bar">
              <span>MTN</span>
              <span>▮▮▮▮</span>
            </div>

            {ussdStep === "learnMenu" && (
              <>
                <div className="ussd-title">LEARN DIGITAL SKILLS</div>

                <p>Choose a topic:</p>

                <div className="ussd-menu">
                  <p>1. Cybersecurity</p>
                  <p>2. Email</p>
                  <p>3. Artificial Intelligence</p>
                  <p>4. Back</p>
                </div>

                <input
                  type="text"
                  inputMode="numeric"
                  maxLength="1"
                  value={ussdInput}
                  onChange={(e) => setUssdInput(e.target.value)}
                  placeholder="Enter option"
                />

                <button
                  onClick={() => {
                    if (ussdInput === "1") {
                      setUssdStep("ussdCybersecurity");
                    } else if (ussdInput === "2") {
                      setUssdStep("ussdEmail");
                    } else if (ussdInput === "3") {
                      setUssdStep("ussdAI");
                    } else if (ussdInput === "4") {
                      setPage("learn");
                    }

                    setUssdInput("");
                  }}
                >
                  Send
                </button>
              </>
            )}

            {ussdStep === "ussdCybersecurity" && (
              <>
                <div className="ussd-title">CYBERSECURITY</div>
                <p>🔐 Use strong passwords.</p>
                <p>🚫 Never share your PIN or password.</p>
                <p>🔗 Don't click suspicious links.</p>
                <p>👤 Verify people before sending money.</p>

                <button onClick={() => setUssdStep("learnMenu")}>
                  Back
                </button>
              </>
            )}

            {ussdStep === "ussdEmail" && (
              <>
                <div className="ussd-title">EMAIL</div>
                <p>📧 Use Compose to write a new email.</p>
                <p>📩 Check the recipient before sending.</p>
                <p>📎 Be careful with unknown attachments.</p>
                <p>🔒 Never share your email password.</p>

                <button onClick={() => setUssdStep("learnMenu")}>
                  Back
                </button>
              </>
            )}

            {ussdStep === "ussdAI" && (
              <>
                <div className="ussd-title">ARTIFICIAL INTELLIGENCE</div>
                <p>🤖 AI helps computers perform intelligent tasks.</p>
                <p>💬 AI can answer questions and help people learn.</p>
                <p>✍️ AI can help with writing and generating ideas.</p>
                <p>🔍 Always verify important AI information.</p>
                <p>🔒 Never share private information with AI.</p>

                <button onClick={() => setUssdStep("learnMenu")}>
                  Back
                </button>
              </>
            )}

            {ussdStep === "menu" && (
              <>
                <div className="ussd-title">DIGITAL BUDDY</div>
                <p>Welcome to Safety Check.</p>
                <p>Choose an option:</p>

                <div className="ussd-menu">
                  <p>1. Check a message</p>
                  <p>2. Safety tips</p>
                  <p>3. Exit</p>
                </div>

                <input
                  type="text"
                  inputMode="numeric"
                  maxLength="1"
                  value={ussdInput}
                  onChange={(e) => setUssdInput(e.target.value)}
                  placeholder="Enter option"
                />

                <button
                  onClick={() => {
                    if (ussdInput === "1") setUssdStep("message");
                    if (ussdInput === "2") setUssdStep("tips");
                    if (ussdInput === "3") setUssdStep("exit");

                    setUssdInput("");
                  }}
                >
                  Send
                </button>
              </>
            )}

            {ussdStep === "message" && (
              <>
                <div className="ussd-title">CHECK MESSAGE</div>
                <p>Enter the suspicious message:</p>

                <textarea
                  value={ussdInput}
                  onChange={(e) => setUssdInput(e.target.value)}
                  placeholder="Type message here..."
                  rows="5"
                />

                <button onClick={handleUSSDMessageCheck}>Check</button>

                <button
                  className="ussd-secondary"
                  onClick={() => {
                    setUssdStep("menu");
                    setUssdInput("");
                  }}
                >
                  Back
                </button>
              </>
            )}

            {ussdStep === "tips" && (
              <>
                <div className="ussd-title">SAFETY TIPS</div>
                <p>• Never share your PIN or OTP.</p>
                <p>• Don't send money to strangers.</p>
                <p>• Verify suspicious messages.</p>
                <p>• Don't click unknown links.</p>

                <button onClick={() => setUssdStep("menu")}>Back</button>
              </>
            )}

            {ussdStep === "result" && (
              <>
                <div className="ussd-title">RESULT</div>

                {scamResult ? (
                  <>
                    <p>
                      Risk: <strong>{scamResult.riskLevel}</strong>
                    </p>
                    <p>Score: {scamResult.score}/100</p>
                    <p>Type: {scamResult.scamCategory}</p>
                  </>
                ) : (
                  <p>Checking message...</p>
                )}

                <button
                  onClick={() => {
                    resetUSSD();
                    setPage("scamCheck");
                  }}
                >
                  Finish
                </button>
              </>
            )}

            {ussdStep === "exit" && (
              <>
                <div className="ussd-title">DIGITAL BUDDY</div>
                <p>Thank you for using Safety Check.</p>
                <p>Stay safe online.</p>

                <button
                  onClick={() => {
                    resetUSSD();
                    setPage("home");
                  }}
                >
                  Close
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    );
  }

  // ==============================
  // CYBERSECURITY
  // ==============================

  if (page === "cybersecurity") {
    return (
      <div className="app">
        <button onClick={() => setPage("learn")}>← Back</button>

        <h1>🔐 Cybersecurity</h1>
        <p>Learn how to protect yourself when using technology.</p>

        <h3>🔑 Use Strong Passwords</h3>
        <p>Use passwords that are difficult for other people to guess.</p>

        <h3>🚫 Don't Share Your PIN</h3>
        <p>Never share your mobile money PIN or password.</p>

        <h3>🔗 Be Careful With Links</h3>
        <p>Don't click suspicious links sent through SMS or email.</p>

        <h2>🎯 Ready to Test Yourself?</h2>

        <button
          className="primary-button"
          onClick={() => startQuiz("quiz")}
        >
          Take Quiz
        </button>
      </div>
    );
  }

  // ==============================
  // EMAIL
  // ==============================

  if (page === "email") {
    return (
      <div className="app">
        <button onClick={() => setPage("learn")}>← Back</button>

        <h1>📧 Email</h1>
        <p>Learn how to use email to communicate safely.</p>

        <h3>📩 Sending an Email</h3>
        <p>Click Compose, enter the recipient, write your message and send.</p>

        <h3>📎 Attachments</h3>
        <p>Be careful when opening attachments from unknown senders.</p>

        <h3>🔒 Keep Your Email Safe</h3>
        <p>Never share your email password.</p>

        <button
          className="primary-button"
          onClick={() => startQuiz("emailQuiz")}
        >
          Take Email Quiz
        </button>
      </div>
    );
  }

  // ==============================
  // AI LESSON
  // ==============================

  if (page === "ai") {
    return (
      <div className="app">
        <button onClick={() => setPage("learn")}>← Back</button>

        <h1>🤖 Artificial Intelligence</h1>

        <p>
          Artificial Intelligence is technology that allows computers to perform
          tasks that normally require human intelligence.
        </p>

        <h3>💬 AI Can Answer Questions</h3>
        <p>AI tools can help explain topics and answer questions.</p>

        <h3>✍️ AI Can Help With Work</h3>
        <p>AI can help with writing, ideas and learning.</p>

        <h3>⚠️ AI Can Make Mistakes</h3>
        <p>Always verify important information provided by AI.</p>

        <h3>🔒 Protect Your Information</h3>
        <p>Never share passwords, PINs or sensitive information.</p>

        <button
          className="primary-button"
          onClick={() => startQuiz("aiQuiz")}
        >
          Take AI Quiz
        </button>
      </div>
    );
  }

  // ==============================
  // SCAM CHECK
  // ==============================

  if (page === "scamCheck") {
    return (
      <div className="app">
        <button className="back-button" onClick={() => setPage("home")}>
          ← Back
        </button>

        <h1>🛡️ Safety Check</h1>
        <p>Not sure about a message? Let's look for warning signs.</p>

        <button
          className="ussd-button"
          onClick={() => {
            resetUSSD();
            setPage("ussd");
          }}
        >
          📱 Use USSD
        </button>

        <div className="scam-card">
          <textarea
            value={scamMessage}
            onChange={(e) => setScamMessage(e.target.value)}
            placeholder="Paste a suspicious message here..."
            rows="7"
          />

          <button
            className="primary-button"
            onClick={() => analyzeScamMessage()}
            disabled={!scamMessage.trim() || isCheckingScam}
          >
            {isCheckingScam ? "Checking..." : "Check Message"}
          </button>
        </div>

        {scamResult && (
          <div className="scam-result">
            <h2>{scamResult.riskLevel} RISK</h2>
            <h3>Score: {scamResult.score}/100</h3>
            <p>{scamResult.riskDescription}</p>
            <p>
              <strong>Category:</strong> {scamResult.scamCategory}
            </p>

            <h3>Warning Signs</h3>

            {scamResult.warningSigns.map((warning, index) => (
              <div key={index}>
                <strong>
                  {warning.icon} {warning.title}
                </strong>
                <p>{warning.description}</p>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  // ==============================
  // QUIZZES
  // ==============================

  if (page === "quiz") {
    return (
      <div className="app">
        <button onClick={() => setPage("cybersecurity")}>← Back</button>

        <h1>🎯 Cybersecurity Quiz</h1>
        <h2>
          Question {questionNumber + 1} of {questions.length}
        </h2>

        <h3>{questions[questionNumber].question}</h3>

        {questions[questionNumber].options.map((option) => (
          <button
            key={option}
            className="quiz-option"
            onClick={() => answerQuestion(option, questions, "result")}
          >
            {option}
          </button>
        ))}
      </div>
    );
  }

  if (page === "emailQuiz") {
    return (
      <div className="app">
        <button onClick={() => setPage("email")}>← Back</button>

        <h1>🎯 Email Quiz</h1>
        <h2>
          Question {questionNumber + 1} of {emailQuestions.length}
        </h2>

        <h3>{emailQuestions[questionNumber].question}</h3>

        {emailQuestions[questionNumber].options.map((option) => (
          <button
            key={option}
            className="quiz-option"
            onClick={() =>
              answerQuestion(option, emailQuestions, "emailResult")
            }
          >
            {option}
          </button>
        ))}
      </div>
    );
  }

  if (page === "aiQuiz") {
    return (
      <div className="app">
        <button onClick={() => setPage("ai")}>← Back</button>

        <h1>🎯 Artificial Intelligence Quiz</h1>
        <h2>
          Question {questionNumber + 1} of {aiQuestions.length}
        </h2>

        <h3>{aiQuestions[questionNumber].question}</h3>

        {aiQuestions[questionNumber].options.map((option) => (
          <button
            key={option}
            className="quiz-option"
            onClick={() => answerQuestion(option, aiQuestions, "aiResult")}
          >
            {option}
          </button>
        ))}
      </div>
    );
  }

  // ==============================
  // RESULTS
  // ==============================

  const resultData =
    page === "emailResult"
      ? { title: "🏆 Email Quiz Complete!", total: emailQuestions.length }
      : page === "aiResult"
        ? { title: "🏆 AI Quiz Complete!", total: aiQuestions.length }
        : { title: "🏆 Quiz Complete!", total: questions.length };

  return (
    <div className="app">
      <h1>{resultData.title}</h1>

      <h2>
        Your Score: {score} / {resultData.total}
      </h2>

      <p>Great job! Keep learning and staying safe online.</p>

      <button
        className="primary-button"
        onClick={() => {
          setQuestionNumber(0);
          setScore(0);
          setPage("learn");
        }}
      >
        Back to Digital Skills
      </button>
    </div>
  );
}

export default App;