import { useState } from "react";
import "./App.css";

function App() {
  const [page, setPage] = useState("home");
  const [questionNumber, setQuestionNumber] = useState(0);
  const [score, setScore] = useState(0);

  // CYBERSECURITY QUIZ QUESTIONS
  const questions = [
    {
      question: "Should you share your mobile money PIN with someone?",
      options: ["Yes", "No"],
      correct: "No",
    },
    {
      question: "What should you do before clicking a suspicious link?",
      options: [
        "Click it immediately",
        "Check and verify the link",
        "Share it with everyone",
      ],
      correct: "Check and verify the link",
    },
    {
      question: "Which password is stronger?",
      options: ["123456", "password", "MyP@ssw0rd!2026"],
      correct: "MyP@ssw0rd!2026",
    },
  ];

  // EMAIL QUIZ QUESTIONS
  const emailQuestions = [
    {
      question: "What is email mainly used for?",
      options: [
        "Sending and receiving messages",
        "Cooking food",
        "Taking photos",
        "Charging a phone",
      ],
      correct: "Sending and receiving messages",
    },
    {
      question: "Which button is commonly used to start writing a new email?",
      options: [
        "Delete",
        "Compose",
        "Refresh",
        "Download",
      ],
      correct: "Compose",
    },
    {
      question:
        "What should you do if you receive an email from an unknown sender with a suspicious attachment?",
      options: [
        "Open the attachment immediately",
        "Forward it to everyone",
        "Be careful and avoid opening it",
        "Reply with your password",
      ],
      correct: "Be careful and avoid opening it",
    },
  ];

  // AI QUIZ QUESTIONS
  const aiQuestions = [
    {
      question: "What is Artificial Intelligence (AI)?",
      options: [
        "Technology that allows computers to perform tasks that normally require human intelligence",
        "A type of mobile phone",
        "A social media application",
        "A computer cable",
      ],
      correct:
        "Technology that allows computers to perform tasks that normally require human intelligence",
    },
    {
      question: "Which of these is an example of Artificial Intelligence?",
      options: [
        "A voice assistant answering questions",
        "A notebook",
        "A USB cable",
        "A normal light bulb",
      ],
      correct: "A voice assistant answering questions",
    },
    {
      question: "What should you do before trusting important information generated by AI?",
      options: [
        "Share it immediately",
        "Verify the information",
        "Ignore it completely",
        "Send it to everyone",
      ],
      correct: "Verify the information",
    },
  ];

  return (
    <div className="app">

      {/* HOME PAGE */}
      {page === "home" ? (
        <>
          <h1>Digital Buddy</h1>

          <p className="subtitle">
            Learn, stay safe, and understand technology.
          </p>

          <h2>What would you like to do?</h2>

          <div className="cards">

            <button
              className="card"
              onClick={() => setPage("learn")}
            >
              <div className="icon">📚</div>
              <h3>Learn Digital Skills</h3>
              <p>Learn how to use technology safely.</p>
            </button>

            <button className="card">
              <div className="icon">🛡️</div>
              <h3>Check for Scams</h3>
              <p>Check suspicious messages.</p>
            </button>

            <button className="card">
              <div className="icon">🤖</div>
              <h3>Ask Digital Assistant</h3>
              <p>Ask questions about technology.</p>
            </button>

          </div>
        </>

      ) : page === "learn" ? (

        /* LEARN DIGITAL SKILLS PAGE */
        <>
          <button onClick={() => setPage("home")}>
            ← Back
          </button>

          <h1>📚 Learn Digital Skills</h1>

          <p>
            Choose a topic you would like to learn.
          </p>

          {/* CYBERSECURITY */}
          <button
            className="lesson-button"
            onClick={() => setPage("cybersecurity")}
          >
            <h3>🔐 Cybersecurity</h3>

            <p>
              Learn how to protect your accounts and personal information.
            </p>
          </button>

          {/* EMAIL */}
          <button
            className="lesson-button"
            onClick={() => setPage("email")}
          >
            <h3>📧 Email</h3>

            <p>
              Learn how to create and use email safely.
            </p>
          </button>

          {/* ARTIFICIAL INTELLIGENCE */}
          <button
            className="lesson-button"
            onClick={() => setPage("ai")}
          >
            <h3>🤖 Artificial Intelligence</h3>

            <p>
              Learn how to use AI safely and effectively.
            </p>
          </button>
        </>

      ) : page === "cybersecurity" ? (

        /* CYBERSECURITY PAGE */
        <>
          <button onClick={() => setPage("learn")}>
            ← Back
          </button>

          <h1>🔐 Cybersecurity</h1>

          <p>
            Learn how to protect yourself when using technology and the internet.
          </p>

          <h2>How to Stay Safe Online</h2>

          <h3>🔑 Use Strong Passwords</h3>

          <p>
            Create passwords that are difficult for other people to guess.
            Avoid using simple information such as your name or birthday.
          </p>

          <h3>🚫 Don't Share Your PIN</h3>

          <p>
            Never share your mobile money PIN, bank PIN, or password with anyone.
          </p>

          <h3>🔗 Be Careful With Links</h3>

          <p>
            Don't click suspicious links sent through SMS, WhatsApp, or email.
          </p>

          <h3>👤 Verify People</h3>

          <p>
            Before sending money or personal information, make sure you know
            who you are dealing with.
          </p>

          <h2>🎯 Ready to Test Yourself?</h2>

          <button
            className="primary-button"
            onClick={() => setPage("quiz")}
          >
            Take Quiz
          </button>
        </>

      ) : page === "email" ? (

        /* EMAIL PAGE */
        <>
          <button onClick={() => setPage("learn")}>
            ← Back
          </button>

          <h1>📧 Email</h1>

          <p>
            Learn how to use email to communicate and share information online.
          </p>

          <h2>How to Use Email</h2>

          <h3>📩 Sending an Email</h3>

          <p>
            Open your email app, click Compose, enter the recipient's email
            address, write your message, and click Send.
          </p>

          <h3>📎 Attaching a File</h3>

          <p>
            You can attach photos, documents, and other files to an email.
            Click the attachment icon and choose the file you want to send.
          </p>

          <h3>👤 Check the Recipient</h3>

          <p>
            Always check that you have entered the correct email address
            before sending your message.
          </p>

          <h3>🔒 Keep Your Email Safe</h3>

          <p>
            Never share your email password with other people. Be careful
            when opening links or attachments from unknown senders.
          </p>

          <h2>🎯 Ready to Test Yourself?</h2>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("emailQuiz");
            }}
          >
            Take Email Quiz
          </button>
        </>

      ) : page === "ai" ? (

        /* ARTIFICIAL INTELLIGENCE PAGE */
        <>
          <button onClick={() => setPage("learn")}>
            ← Back
          </button>

          <h1>🤖 Artificial Intelligence</h1>

          <p>
            Learn what Artificial Intelligence is and how to use it
            safely and effectively.
          </p>

          <h2>🧠 What is Artificial Intelligence?</h2>

          <p>
            Artificial Intelligence, commonly called AI, is technology
            that allows computers to perform tasks that normally require
            human intelligence.
          </p>

          <h3>💬 AI Can Answer Questions</h3>

          <p>
            AI tools can answer questions, explain difficult topics,
            translate languages, and help users find information.
          </p>

          <h3>✍️ AI Can Help With Work</h3>

          <p>
            AI can help people write messages, summarize information,
            generate ideas, and learn new skills.
          </p>

          <h3>📱 Examples of AI</h3>

          <p>
            AI is used in voice assistants, recommendation systems,
            chatbots, translation tools, facial recognition, and
            some smartphone applications.
          </p>

          <h3>✅ Benefits of AI</h3>

          <p>
            AI can help people save time, learn faster, automate
            repetitive tasks, and access information more easily.
          </p>

          <h3>⚠️ AI Can Make Mistakes</h3>

          <p>
            AI does not always provide correct information. It can
            sometimes give inaccurate or incomplete answers.
          </p>

          <h3>🔍 Verify AI Information</h3>

          <p>
            Always check important information provided by AI using
            trusted and reliable sources.
          </p>

          <h3>🔒 Protect Your Personal Information</h3>

          <p>
            Avoid sharing passwords, PINs, private documents, financial
            information, or other sensitive information with AI tools.
          </p>

          <h3>🤝 Use AI Responsibly</h3>

          <p>
            Use AI as a helpful tool, but remember that you are
            responsible for how you use the information it provides.
          </p>

          <h2>🎯 Ready to Test Yourself?</h2>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("aiQuiz");
            }}
          >
            Take AI Quiz
          </button>
        </>

      ) : page === "quiz" ? (

        /* CYBERSECURITY QUIZ */
        <>
          <button onClick={() => setPage("cybersecurity")}>
            ← Back
          </button>

          <h1>🎯 Cybersecurity Quiz</h1>

          <h2>
            Question {questionNumber + 1} of {questions.length}
          </h2>

          <h3>
            {questions[questionNumber].question}
          </h3>

          {questions[questionNumber].options.map((option) => (
            <button
              key={option}
              className="quiz-option"
              onClick={() => {
                if (option === questions[questionNumber].correct) {
                  setScore(score + 1);
                }

                if (questionNumber < questions.length - 1) {
                  setQuestionNumber(questionNumber + 1);
                } else {
                  setPage("result");
                }
              }}
            >
              {option}
            </button>
          ))}
        </>

      ) : page === "emailQuiz" ? (

        /* EMAIL QUIZ */
        <>
          <button onClick={() => setPage("email")}>
            ← Back
          </button>

          <h1>🎯 Email Quiz</h1>

          <h2>
            Question {questionNumber + 1} of {emailQuestions.length}
          </h2>

          <h3>
            {emailQuestions[questionNumber].question}
          </h3>

          {emailQuestions[questionNumber].options.map((option) => (
            <button
              key={option}
              className="quiz-option"
              onClick={() => {
                if (
                  option === emailQuestions[questionNumber].correct
                ) {
                  setScore(score + 1);
                }

                if (
                  questionNumber < emailQuestions.length - 1
                ) {
                  setQuestionNumber(questionNumber + 1);
                } else {
                  setPage("emailResult");
                }
              }}
            >
              {option}
            </button>
          ))}
        </>

      ) : page === "emailResult" ? (

        /* EMAIL RESULT */
        <>
          <h1>🏆 Email Quiz Complete!</h1>

          <h2>
            Your Score: {score} / {emailQuestions.length}
          </h2>

          <p>
            Great job! Keep learning how to use email safely.
          </p>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("learn");
            }}
          >
            Back to Digital Skills
          </button>
        </>

      ) : page === "aiQuiz" ? (

        /* AI QUIZ */
        <>
          <button onClick={() => setPage("ai")}>
            ← Back
          </button>

          <h1>🎯 Artificial Intelligence Quiz</h1>

          <h2>
            Question {questionNumber + 1} of {aiQuestions.length}
          </h2>

          <h3>
            {aiQuestions[questionNumber].question}
          </h3>

          {aiQuestions[questionNumber].options.map((option) => (
            <button
              key={option}
              className="quiz-option"
              onClick={() => {
                if (
                  option === aiQuestions[questionNumber].correct
                ) {
                  setScore(score + 1);
                }

                if (
                  questionNumber < aiQuestions.length - 1
                ) {
                  setQuestionNumber(questionNumber + 1);
                } else {
                  setPage("aiResult");
                }
              }}
            >
              {option}
            </button>
          ))}
        </>

      ) : page === "aiResult" ? (

        /* AI RESULT */
        <>
          <h1>🏆 AI Quiz Complete!</h1>

          <h2>
            Your Score: {score} / {aiQuestions.length}
          </h2>

          <p>
            Great job! Keep learning how to use Artificial Intelligence
            safely and effectively.
          </p>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("learn");
            }}
          >
            Back to Digital Skills
          </button>
        </>

      ) : (

        /* CYBERSECURITY RESULT */
        <>
          <h1>🏆 Quiz Complete!</h1>

          <h2>
            Your Score: {score} / {questions.length}
          </h2>

          <p>
            Great job! Keep learning how to stay safe online.
          </p>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("home");
            }}
          >
            Back to Home
          </button>
        </>
      )}

    </div>
  );
}

export default App;