import { useState } from "react";
import "./App.css";

function App() {
  const [page, setPage] = useState("home");
  const [questionNumber, setQuestionNumber] = useState(0);
  const [score, setScore] = useState(0);

  const [scamMessage, setScamMessage] = useState("");
  const [scamResult, setScamResult] = useState(null);
  const [isCheckingScam, setIsCheckingScam] = useState(false);

  // CYBERSECURITY QUIZ QUESTIONS
  const questions = [
    {
      question: "Should you share your mobile money PIN with someone?",
      options: ["Yes", "No"],
      correct: "No",
    },
    {
      question: "What should you do before clicking a suspicious link?",
      options: [
        "Click it immediately",
        "Check and verify the link",
        "Share it with everyone",
      ],
      correct: "Check and verify the link",
    },
    {
      question: "Which password is stronger?",
      options: ["123456", "password", "MyP@ssw0rd!2026"],
      correct: "MyP@ssw0rd!2026",
    },
  ];

  // EMAIL QUIZ QUESTIONS
  const emailQuestions = [
    {
      question: "What is email mainly used for?",
      options: [
        "Sending and receiving messages",
        "Cooking food",
        "Taking photos",
        "Charging a phone",
      ],
      correct: "Sending and receiving messages",
    },
    {
      question: "Which button is commonly used to start writing a new email?",
      options: ["Delete", "Compose", "Refresh", "Download"],
      correct: "Compose",
    },
    {
      question:
        "What should you do if you receive an email from an unknown sender with a suspicious attachment?",
      options: [
        "Open the attachment immediately",
        "Forward it to everyone",
        "Be careful and avoid opening it",
        "Reply with your password",
      ],
      correct: "Be careful and avoid opening it",
    },
  ];

  // AI QUIZ QUESTIONS
  const aiQuestions = [
    {
      question: "What is Artificial Intelligence (AI)?",
      options: [
        "Technology that allows computers to perform tasks that normally require human intelligence",
        "A type of mobile phone",
        "A social media application",
        "A computer cable",
      ],
      correct:
        "Technology that allows computers to perform tasks that normally require human intelligence",
    },
    {
      question: "Which of these is an example of Artificial Intelligence?",
      options: [
        "A voice assistant answering questions",
        "A notebook",
        "A USB cable",
        "A normal light bulb",
      ],
      correct: "A voice assistant answering questions",
    },
    {
      question:
        "What should you do before trusting important information generated by AI?",
      options: [
        "Share it immediately",
        "Verify the information",
        "Ignore it completely",
        "Send it to everyone",
      ],
      correct: "Verify the information",
    },
  ];

  const analyzeScamMessage = () => {
    if (!scamMessage.trim()) {
      return;
    }

    setIsCheckingScam(true);
    setScamResult(null);

    setTimeout(() => {
      const message = scamMessage.toLowerCase();

      let score = 0;
      const warningSigns = [];

      // Urgency
      if (
        message.includes("urgent") ||
        message.includes("immediately") ||
        message.includes("within") ||
        message.includes("now") ||
        message.includes("hurry") ||
        message.includes("minutes")
      ) {
        score += 20;

        warningSigns.push({
          icon: "⏰",
          title: "Creates urgency",
          description:
            "The sender is pressuring you to act quickly instead of giving you time to verify the message.",
        });
      }

      // PIN / OTP / password
      if (
        message.includes("pin") ||
        message.includes("otp") ||
        message.includes("password") ||
        message.includes("passcode") ||
        message.includes("verification code")
      ) {
        score += 35;

        warningSigns.push({
          icon: "🔐",
          title: "Requests sensitive information",
          description:
            "Legitimate organizations should not ask you to reveal your PIN, password, or OTP.",
        });
      }

      // Money
      if (
        message.includes("send money") ||
        message.includes("pay") ||
        message.includes("payment") ||
        message.includes("transfer") ||
        message.includes("fee") ||
        message.includes("deposit")
      ) {
        score += 25;

        warningSigns.push({
          icon: "💰",
          title: "Requests money",
          description: "The message asks you to send money or make a payment.",
        });
      }

      // Prize / reward
      if (
        message.includes("won") ||
        message.includes("winner") ||
        message.includes("prize") ||
        message.includes("reward") ||
        message.includes("congratulations") ||
        message.includes("lottery")
      ) {
        score += 20;

        warningSigns.push({
          icon: "🎁",
          title: "Unexpected reward",
          description:
            "The message promises a prize, reward, or money that you may not have expected.",
        });
      }

      // Suspicious links
      if (
        message.includes("http://") ||
        message.includes("https://") ||
        message.includes("www.") ||
        message.includes(".com/")
      ) {
        score += 15;

        warningSigns.push({
          icon: "🔗",
          title: "Contains a link",
          description:
            "Be careful with links in unexpected messages. Verify the destination before opening them.",
        });
      }

      // Threats
      if (
        message.includes("account will be closed") ||
        message.includes("account will be blocked") ||
        message.includes("arrest") ||
        message.includes("police") ||
        message.includes("legal action")
      ) {
        score += 20;

        warningSigns.push({
          icon: "⚠️",
          title: "Uses fear or threats",
          description:
            "The sender may be using fear or threats to pressure you into acting.",
        });
      }

      score = Math.min(score, 100);

      let riskLevel = "LOW";
      let riskDescription =
        "We found few obvious warning signs, but always verify unexpected messages.";

      if (score >= 70) {
        riskLevel = "HIGH";
        riskDescription =
          "This message contains several common warning signs associated with scams.";
      } else if (score >= 40) {
        riskLevel = "SUSPICIOUS";
        riskDescription =
          "This message contains warning signs that you should investigate before taking action.";
      } else if (score >= 20) {
        riskLevel = "CAUTION";
        riskDescription =
          "There are some warning signs. Be careful and verify the sender.";
      }

      let scamCategory = "General Scam";

      if (
        message.includes("mobile money") ||
        message.includes("momo") ||
        message.includes("airtel money") ||
        message.includes("mtn") ||
        message.includes("withdraw") ||
        message.includes("deposit") ||
        message.includes("mobile money pin")
      ) {
        scamCategory = "Mobile Money Scam";
      } else if (
        message.includes("job") ||
        message.includes("employment") ||
        message.includes("vacancy") ||
        message.includes("salary") ||
        message.includes("work from home") ||
        message.includes("interview")
      ) {
        scamCategory = "Job Scam";
      } else if (
        message.includes("scholarship") ||
        message.includes("university") ||
        message.includes("school") ||
        message.includes("admission") ||
        message.includes("tuition") ||
        message.includes("education")
      ) {
        scamCategory = "Education Scam";
      } else if (
        message.includes("love") ||
        message.includes("relationship") ||
        message.includes("girlfriend") ||
        message.includes("boyfriend") ||
        message.includes("romance") ||
        message.includes("marriage")
      ) {
        scamCategory = "Romance Scam";
      } else if (
        message.includes("prize") ||
        message.includes("winner") ||
        message.includes("won") ||
        message.includes("lottery") ||
        message.includes("reward") ||
        message.includes("congratulations")
      ) {
        scamCategory = "Prize Scam";
      } else if (
        message.includes("account") ||
        message.includes("bank") ||
        message.includes("password") ||
        message.includes("otp") ||
        message.includes("verification code") ||
        message.includes("login")
      ) {
        scamCategory = "Account / Identity Scam";
      } else if (
        message.includes("police") ||
        message.includes("arrest") ||
        message.includes("court") ||
        message.includes("government") ||
        message.includes("tax")
      ) {
        scamCategory = "Impersonation Scam";
      }

      setScamResult({
        score,
        riskLevel,
        riskDescription,
        warningSigns,
        scamCategory,
      });

      setIsCheckingScam(false);
    }, 900);
  };

  const highlightScamWords = (text) => {
    const suspiciousWords = [
      "urgent",
      "immediately",
      "now",
      "hurry",
      "minutes",
      "pin",
      "otp",
      "password",
      "passcode",
      "verification code",
      "send money",
      "pay",
      "payment",
      "transfer",
      "fee",
      "deposit",
      "won",
      "winner",
      "prize",
      "reward",
      "congratulations",
      "lottery",
      "http://",
      "https://",
      "www.",
      "account will be closed",
      "account will be blocked",
      "arrest",
      "police",
      "legal action",
    ];

    const escapedWords = suspiciousWords.map((word) =>
      word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
    );

    const pattern = new RegExp(`(${escapedWords.join("|")})`, "gi");

    return text.split(pattern).map((part, index) => {
      const isSuspicious = suspiciousWords.some(
        (word) => word.toLowerCase() === part.toLowerCase(),
      );

      if (isSuspicious) {
        return (
          <mark className="suspicious-highlight" key={index}>
            {part}
          </mark>
        );
      }

      return part;
    });
  };

  const getScamAdvice = (category) => {
  const advice = {
    "Mobile Money Scam": {
      icon: "📱",
      title: "Protect your mobile money",
      points: [
        "Never share your mobile-money PIN or OTP.",
        "Don't send money because of an unexpected message.",
        "Contact your mobile-money provider using an official number or app.",
      ],
    },

    "Job Scam": {
      icon: "💼",
      title: "Verify the job opportunity",
      points: [
        "Don't pay money just to apply for or receive a job.",
        "Research the company using its official website.",
        "Verify the vacancy with the company's official contact information.",
      ],
    },

    "Education Scam": {
      icon: "🎓",
      title: "Verify the education offer",
      points: [
        "Contact the school or university directly.",
        "Don't pay fees through an unverified link or personal number.",
        "Check the institution's official website for scholarship information.",
      ],
    },

    "Romance Scam": {
      icon: "❤️",
      title: "Protect yourself from romance scams",
      points: [
        "Don't send money to someone you only know online.",
        "Be cautious if someone creates an emotional emergency.",
        "Verify the person's identity before sharing personal or financial information.",
      ],
    },

    "Prize Scam": {
      icon: "🎁",
      title: "Be careful with unexpected prizes",
      points: [
        "Don't pay a fee to claim a prize you didn't enter.",
        "Don't share your PIN, password, or OTP.",
        "Verify the promotion through the organization's official website or contact.",
      ],
    },

    "Account / Identity Scam": {
      icon: "🔐",
      title: "Protect your account",
      points: [
        "Never share your password, PIN, or OTP.",
        "Don't log in through links sent in unexpected messages.",
        "Contact the organization directly if you think your account has a problem.",
      ],
    },

    "Impersonation Scam": {
      icon: "🎭",
      title: "Verify who contacted you",
      points: [
        "Don't trust a message simply because it uses an official name or logo.",
        "Contact the organization through an official channel.",
        "Don't send money or personal information until the request is verified.",
      ],
    },

    "General Scam": {
      icon: "🛡️",
      title: "Stay safe",
      points: [
        "Don't rush into taking action.",
        "Verify the sender independently.",
        "Never share passwords, PINs, or OTPs.",
      ],
    },
  };

  return advice[category] || advice["General Scam"];
};

  return (
    <div className="app">
      {/* HOME PAGE */}
      {page === "home" ? (
        <>
          <h1>Digital Buddy</h1>

          <p className="subtitle">
            Learn, stay safe, and understand technology.
          </p>

          <h2>What would you like to do?</h2>

          <div className="cards">
            <button className="card" onClick={() => setPage("learn")}>
              <div className="icon">📚</div>
              <h3>Learn Digital Skills</h3>
              <p>Learn how to use technology safely.</p>
            </button>

            <button className="card" onClick={() => setPage("scamCheck")}>
              <div className="icon">🛡️</div>
              <h3>Check For Scams</h3>
              <p>Check suspicious messages.</p>
            </button>

            <button className="card">
              <div className="icon">🤖</div>
              <h3>Ask Digital Assistant</h3>
              <p>Ask questions about technology.</p>
            </button>
          </div>
        </>
      ) : page === "scamCheck" ? (
        /* SCAM CHECK PAGE */
        <>
          <button
            className="back-button"
            onClick={() => {
              setPage("home");
              setScamResult(null);
            }}
          >
            ← Back
          </button>

          <div className="scam-header">
            <div className="scam-icon">🛡️</div>

            <h1>Safety Check</h1>

            <p className="subtitle">
              Not sure about a message? Let's look for warning signs.
            </p>
          </div>

          <div className="scam-card">
            <label htmlFor="scam-message">Paste the suspicious message</label>

            <textarea
              id="scam-message"
              value={scamMessage}
              onChange={(event) => setScamMessage(event.target.value)}
              placeholder="Example: Congratulations! You have won..."
              rows="7"
            />

            <p className="privacy-note">
              🔒 Don't include passwords, PINs, OTPs, or other sensitive
              information.
            </p>

            <div className="scam-actions">
              <button
                className="example-button"
                onClick={() =>
                  setScamMessage(
                    "Congratulations! You have won UGX 500,000. Send your mobile money PIN within 10 minutes to claim your prize: https://example.com/claim",
                  )
                }
              >
                Try an example
              </button>

              <button
                className="primary-button"
                onClick={analyzeScamMessage}
                disabled={!scamMessage.trim() || isCheckingScam}
              >
                {isCheckingScam ? "Checking..." : "Check Message"}
              </button>
            </div>
          </div>

          {isCheckingScam && (
            <div className="checking-card">
              <div className="loading-icon">🔎</div>

              <h2>Checking for warning signs...</h2>

              <p>We're looking for common scam patterns.</p>
            </div>
          )}

          {scamResult && !isCheckingScam && (
            <div className="scam-result">
              <div
                className={`risk-card risk-${scamResult.riskLevel.toLowerCase()}`}
              >
                <div className="risk-top">
                  <div className="risk-icon">
                    {scamResult.riskLevel === "HIGH"
                      ? "🚨"
                      : scamResult.riskLevel === "SUSPICIOUS"
                        ? "⚠️"
                        : scamResult.riskLevel === "CAUTION"
                          ? "🟡"
                          : "🟢"}
                  </div>

                  <div className="risk-heading">
                    <span className="risk-label">Risk Assessment</span>

                    <h2>
                      {scamResult.riskLevel === "HIGH"
                        ? "Potential Scam"
                        : scamResult.riskLevel === "SUSPICIOUS"
                          ? "Suspicious Message"
                          : scamResult.riskLevel === "CAUTION"
                            ? "Proceed With Caution"
                            : "Low Risk"}
                    </h2>
                    <span className="scam-category">
                      🏷️ {scamResult.scamCategory}
                    </span>
                  </div>

                  <div className="risk-score">
                    <strong>{scamResult.score}</strong>
                    <span>/100</span>
                  </div>
                </div>

                <p className="risk-description">{scamResult.riskDescription}</p>

                <div className="risk-meter">
                  <div
                    className="risk-meter-fill"
                    style={{
                      width: `${scamResult.score}%`,
                    }}
                  />
                </div>

                <div className="risk-meter-labels">
                  <span>Low Risk</span>
                  <span>High Risk</span>
                </div>
              </div>

              <div className="message-preview">
                <div className="message-preview-header">
                  <h2>🔎 Message Analysis</h2>

                  <span>Highlighted warning signs</span>
                </div>

                <div className="message-content">
                  {highlightScamWords(scamMessage)}
                </div>

                <div className="highlight-legend">
                  <span>
                    <mark className="legend-highlight">Warning sign</mark>
                  </span>

                  <span>Words or phrases that deserve extra attention</span>
                </div>
              </div>

              <div className="warning-section">
                <h2>Why we're concerned</h2>

                {scamResult.warningSigns.length === 0 ? (
                  <div className="no-warning">
                    <span>✓</span>

                    <p>
                      We didn't detect obvious scam warning signs. However,
                      always verify unexpected messages.
                    </p>
                  </div>
                ) : (
                  scamResult.warningSigns.map((warning, index) => (
                    <div
                      className="warning-item"
                      key={`${warning.title}-${index}`}
                    >
                      <div className="warning-icon">{warning.icon}</div>

                      <div>
                        <h3>{warning.title}</h3>

                        <p>{warning.description}</p>
                      </div>
                    </div>
                  ))
                )}
              </div>

              <div className="safety-actions-card">

  <div className="advice-header">

    <div className="advice-icon">
      {getScamAdvice(scamResult.scamCategory).icon}
    </div>

    <div>
      <span className="advice-label">
        Safety Advice
      </span>

      <h2>
        {getScamAdvice(scamResult.scamCategory).title}
      </h2>
    </div>

  </div>

  <div className="advice-list">

    {getScamAdvice(scamResult.scamCategory).points.map(
      (point, index) => (
        <div
          className="advice-item"
          key={index}
        >

          <div className="advice-number">
            {index + 1}
          </div>

          <p>{point}</p>

        </div>
      )
    )}

  </div>

</div>

              <button
                className="secondary-button"
                onClick={() => {
                  setScamMessage("");
                  setScamResult(null);
                }}
              >
                Check Another Message
              </button>

              <p className="disclaimer">
                DigitalBridge provides educational guidance. A risk assessment
                does not guarantee that a message is fraudulent or safe.
              </p>
            </div>
          )}
        </>
      ) : page === "learn" ? (
        /* LEARN DIGITAL SKILLS PAGE */
        <>
          <button onClick={() => setPage("home")}>← Back</button>

          <h1>📚 Learn Digital Skills</h1>

          <p>Choose a topic you would like to learn.</p>

          {/* CYBERSECURITY */}
          <button
            className="lesson-button"
            onClick={() => setPage("cybersecurity")}
          >
            <h3>🔐 Cybersecurity</h3>

            <p>Learn how to protect your accounts and personal information.</p>
          </button>

          {/* EMAIL */}
          <button className="lesson-button" onClick={() => setPage("email")}>
            <h3>📧 Email</h3>

            <p>Learn how to create and use email safely.</p>
          </button>

          {/* ARTIFICIAL INTELLIGENCE */}
          <button className="lesson-button" onClick={() => setPage("ai")}>
            <h3>🤖 Artificial Intelligence</h3>

            <p>Learn how to use AI safely and effectively.</p>
          </button>
        </>
      ) : page === "cybersecurity" ? (
        /* CYBERSECURITY PAGE */
        <>
          <button onClick={() => setPage("learn")}>← Back</button>

          <h1>🔐 Cybersecurity</h1>

          <p>
            Learn how to protect yourself when using technology and the
            internet.
          </p>

          <h2>How to Stay Safe Online</h2>

          <h3>🔑 Use Strong Passwords</h3>

          <p>
            Create passwords that are difficult for other people to guess. Avoid
            using simple information such as your name or birthday.
          </p>

          <h3>🚫 Don't Share Your PIN</h3>

          <p>
            Never share your mobile money PIN, bank PIN, or password with
            anyone.
          </p>

          <h3>🔗 Be Careful With Links</h3>

          <p>
            Don't click suspicious links sent through SMS, WhatsApp, or email.
          </p>

          <h3>👤 Verify People</h3>

          <p>
            Before sending money or personal information, make sure you know who
            you are dealing with.
          </p>

          <h2>🎯 Ready to Test Yourself?</h2>

          <button className="primary-button" onClick={() => setPage("quiz")}>
            Take Quiz
          </button>
        </>
      ) : page === "email" ? (
        /* EMAIL PAGE */
        <>
          <button onClick={() => setPage("learn")}>← Back</button>

          <h1>📧 Email</h1>

          <p>
            Learn how to use email to communicate and share information online.
          </p>

          <h2>How to Use Email</h2>

          <h3>📩 Sending an Email</h3>

          <p>
            Open your email app, click Compose, enter the recipient's email
            address, write your message, and click Send.
          </p>

          <h3>📎 Attaching a File</h3>

          <p>
            You can attach photos, documents, and other files to an email. Click
            the attachment icon and choose the file you want to send.
          </p>

          <h3>👤 Check the Recipient</h3>

          <p>
            Always check that you have entered the correct email address before
            sending your message.
          </p>

          <h3>🔒 Keep Your Email Safe</h3>

          <p>
            Never share your email password with other people. Be careful when
            opening links or attachments from unknown senders.
          </p>

          <h2>🎯 Ready to Test Yourself?</h2>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("emailQuiz");
            }}
          >
            Take Email Quiz
          </button>
        </>
      ) : page === "ai" ? (
        /* ARTIFICIAL INTELLIGENCE PAGE */
        <>
          <button onClick={() => setPage("learn")}>← Back</button>

          <h1>🤖 Artificial Intelligence</h1>

          <p>
            Learn what Artificial Intelligence is and how to use it safely and
            effectively.
          </p>

          <h2>🧠 What is Artificial Intelligence?</h2>

          <p>
            Artificial Intelligence, commonly called AI, is technology that
            allows computers to perform tasks that normally require human
            intelligence.
          </p>

          <h3>💬 AI Can Answer Questions</h3>

          <p>
            AI tools can answer questions, explain difficult topics, translate
            languages, and help users find information.
          </p>

          <h3>✍️ AI Can Help With Work</h3>

          <p>
            AI can help people write messages, summarize information, generate
            ideas, and learn new skills.
          </p>

          <h3>📱 Examples of AI</h3>

          <p>
            AI is used in voice assistants, recommendation systems, chatbots,
            translation tools, facial recognition, and some smartphone
            applications.
          </p>

          <h3>✅ Benefits of AI</h3>

          <p>
            AI can help people save time, learn faster, automate repetitive
            tasks, and access information more easily.
          </p>

          <h3>⚠️ AI Can Make Mistakes</h3>

          <p>
            AI does not always provide correct information. It can sometimes
            give inaccurate or incomplete answers.
          </p>

          <h3>🔍 Verify AI Information</h3>

          <p>
            Always check important information provided by AI using trusted and
            reliable sources.
          </p>

          <h3>🔒 Protect Your Personal Information</h3>

          <p>
            Avoid sharing passwords, PINs, private documents, financial
            information, or other sensitive information with AI tools.
          </p>

          <h3>🤝 Use AI Responsibly</h3>

          <p>
            Use AI as a helpful tool, but remember that you are responsible for
            how you use the information it provides.
          </p>

          <h2>🎯 Ready to Test Yourself?</h2>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("aiQuiz");
            }}
          >
            Take AI Quiz
          </button>
        </>
      ) : page === "quiz" ? (
        /* CYBERSECURITY QUIZ */
        <>
          <button onClick={() => setPage("cybersecurity")}>← Back</button>

          <h1>🎯 Cybersecurity Quiz</h1>

          <h2>
            Question {questionNumber + 1} of {questions.length}
          </h2>

          <h3>{questions[questionNumber].question}</h3>

          {questions[questionNumber].options.map((option) => (
            <button
              key={option}
              className="quiz-option"
              onClick={() => {
                if (option === questions[questionNumber].correct) {
                  setScore(score + 1);
                }

                if (questionNumber < questions.length - 1) {
                  setQuestionNumber(questionNumber + 1);
                } else {
                  setPage("result");
                }
              }}
            >
              {option}
            </button>
          ))}
        </>
      ) : page === "emailQuiz" ? (
        /* EMAIL QUIZ */
        <>
          <button onClick={() => setPage("email")}>← Back</button>

          <h1>🎯 Email Quiz</h1>

          <h2>
            Question {questionNumber + 1} of {emailQuestions.length}
          </h2>

          <h3>{emailQuestions[questionNumber].question}</h3>

          {emailQuestions[questionNumber].options.map((option) => (
            <button
              key={option}
              className="quiz-option"
              onClick={() => {
                if (option === emailQuestions[questionNumber].correct) {
                  setScore(score + 1);
                }

                if (questionNumber < emailQuestions.length - 1) {
                  setQuestionNumber(questionNumber + 1);
                } else {
                  setPage("emailResult");
                }
              }}
            >
              {option}
            </button>
          ))}
        </>
      ) : page === "emailResult" ? (
        /* EMAIL RESULT */
        <>
          <h1>🏆 Email Quiz Complete!</h1>

          <h2>
            Your Score: {score} / {emailQuestions.length}
          </h2>

          <p>Great job! Keep learning how to use email safely.</p>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("learn");
            }}
          >
            Back to Digital Skills
          </button>
        </>
      ) : page === "aiQuiz" ? (
        /* AI QUIZ */
        <>
          <button onClick={() => setPage("ai")}>← Back</button>

          <h1>🎯 Artificial Intelligence Quiz</h1>

          <h2>
            Question {questionNumber + 1} of {aiQuestions.length}
          </h2>

          <h3>{aiQuestions[questionNumber].question}</h3>

          {aiQuestions[questionNumber].options.map((option) => (
            <button
              key={option}
              className="quiz-option"
              onClick={() => {
                if (option === aiQuestions[questionNumber].correct) {
                  setScore(score + 1);
                }

                if (questionNumber < aiQuestions.length - 1) {
                  setQuestionNumber(questionNumber + 1);
                } else {
                  setPage("aiResult");
                }
              }}
            >
              {option}
            </button>
          ))}
        </>
      ) : page === "aiResult" ? (
        /* AI RESULT */
        <>
          <h1>🏆 AI Quiz Complete!</h1>

          <h2>
            Your Score: {score} / {aiQuestions.length}
          </h2>

          <p>
            Great job! Keep learning how to use Artificial Intelligence safely
            and effectively.
          </p>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("learn");
            }}
          >
            Back to Digital Skills
          </button>
        </>
      ) : (
        /* CYBERSECURITY RESULT */
        <>
          <h1>🏆 Quiz Complete!</h1>

          <h2>
            Your Score: {score} / {questions.length}
          </h2>

          <p>Great job! Keep learning how to stay safe online.</p>

          <button
            className="primary-button"
            onClick={() => {
              setQuestionNumber(0);
              setScore(0);
              setPage("home");
            }}
          >
            Back to Home
          </button>
        </>
      )}
    </div>
  );
}

export default App;
